_inputs:
  date:
    type: date
    label: Published on
    comment: The blog post or site was published on this day.
  layout:
    hidden: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
      values:
        - Accessibility
        - CSS
        - HTML
        - JavaScript
        - Performance
        - Progressive Enhancement
        - Responsive Web Design
        - Web Design
collections_config:
  sites:
    icon: link
    preview:
      gallery:
        text: " "
    _enabled_editors:
      - data
    schemas:
      default:
        path: src/_schemas/site.md
